#####################################
#
#     TASK Configuration File
#     Created by: Gabe McWilliams
#     Date: 2023/04/19
#
#####################################

ENVIRONMENT: development
JOB_TITLE: datto_rmm_api_devices

TASKS:

  - POSITION: 0
    DETAILS:
      TITLE: API [EXTRACT] - datto_rmm - devices # str Storage type that file will be stored
      PURPOSE: EXTRACT # str ["EXTRACT", "TRANSFORM", "LOAD"]
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.
      SCRIPTS: # :list of strings for scripts used
[REDACTED]/.py

    ORIGIN:
      TYPE: api #
      VARS: DATTO_RMM_CONFIG # str api env variable key
      REGION: concord # str region if applicable

    DESTINATION:
      TYPE: dataframe # str
      NAME: df

    DATA:
      VALIDATION: # str future reference of data validation
      QUALITY: bronze # str

    LOGGING:
      LOGS_LOCATION: logs # can be bucket_name or abs(folder path)


  - POSITION: 1
    DETAILS:
      TITLE: DataFrame [TRANSFORM] - datto_rmm - devices # str
      PURPOSE: TRANSFORM # str # ETL etc...
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.
      SCRIPTS:
[REDACTED]/.py

    ORIGIN:
      TYPE: dataframe # str

    DESTINATION:
      TYPE: dataframe # str bucket, db, etc name for root path
      NAME: df_shaped # str bucket name, db name, etc name for root path
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.

    DATA:
      VALIDATION: # str future reference of data validation
      QUALITY: silver # str

    LOGGING:
      LOGS_LOCATION: logs # can be bucket_name or abs(folder path)

  - POSITION: 1
    DETAILS:
      TITLE: DataFrame [TRANSFORM] - datto_rmm - segment_data - ms_patching # str
      PURPOSE: TRANSFORM # str # ETL etc...
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.
      SCRIPTS:
[REDACTED]/.py

    ORIGIN:
      TYPE: dataframe # str

    DESTINATION:
      TYPE: dataframe # str bucket, db, etc name for root path
      NAME: df_shaped # str bucket name, db name, etc name for root path
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.

    DATA:
      VALIDATION: # str future reference of data validation
      QUALITY: silver # str

    LOGGING:
      LOGS_LOCATION: logs # can be bucket_name or abs(folder path)


  - POSITION: 2
    DETAILS:
      TITLE: Local Drive [LOAD] - datto_rmm - devices # str Storage type that file will be stored
      PURPOSE: TRANSFORM # str # ETL etc...
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.
      SCRIPTS:
[REDACTED]/.py

    ORIGIN:
      TYPE: dataframe # str

    DESTINATION:
      TYPE: local_drive # str bucket, db, etc name for root path
      NAME:  # str bucket name, db name, etc name for root path
      PRODUCT: datto_rmm # str platform or source definition for
      SUBJECT: devices # str ie.

    DATA:
      VALIDATION: # str future reference of data validation
      QUALITY: silver # str

    LOGGING:
      LOGS_LOCATION: logs # can be bucket_name or abs(folder path)




